let state=load();let sideFilter='all';let companionFilter='all';
const companionUnlockQuests=new Set(['The Big Dig','Curtain Call','Vault 81 and Hole in the Wall']);
function load(){const base={route:'undecided',spoiler:'warn',weapon:'combat',build:'general',done:{},dlc:[...dlcList],selectedQuest:null,companionProgress:{},selectedCompanion:null};try{const old=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...old,done:{...base.done,...old.done},dlc:old.dlc||base.dlc,companionProgress:{...base.companionProgress,...(old.companionProgress||{})}}}catch{return base}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}const $=x=>document.getElementById(x);
function makeButton(text,active,fn){const b=document.createElement('button');b.textContent=text;if(active)b.classList.add('active');b.onclick=fn;return b}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:document.querySelector('.tabs').offsetTop-8,behavior:'smooth'})}
function showQuestInfo(title,desc,type,id,done){state.selectedQuest={title,desc:desc||describeQuest(title,type),type,id,done:!!done};save();renderQuestPeek()}
function renderQuestPeek(){const q=state.selectedQuest,box=$('questPeek');if(!q){box.classList.add('hidden');return}box.classList.remove('hidden');$('questPeekTitle').textContent=q.title;$('questPeekDesc').textContent=q.desc||describeQuest(q.title,q.type);$('questPeekType').textContent=q.type;$('questPeekState').textContent=q.done?'✓ Checked off':'Not checked off'}
function closeQuestPeek(){state.selectedQuest=null;save();renderQuestPeek()}
function checkItem(title,desc,type,id){const fullDesc=desc||describeQuest(title,type);const l=document.createElement('label');l.className='item'+(state.done[id]?' done':'');l.title='Click for quest info';const c=document.createElement('input');c.type='checkbox';c.checked=!!state.done[id];c.onchange=()=>{state.done[id]=c.checked;showQuestInfo(title,fullDesc,type,id,c.checked);renderProgress();renderCurrentLists()};const d=document.createElement('div');d.innerHTML='<h3>'+title+'</h3>'+(desc?'<p>'+desc+'</p>':'')+'<span class="tag '+(type==='Danger'?'danger-tag':'')+'">'+type+'</span>';l.onclick=e=>{if(e.target!==c)showQuestInfo(title,fullDesc,type,id,c.checked)};l.append(c,d);return l}
function renderControls(){const r=$('routeBtns');r.innerHTML='';routeList.forEach(([id,label])=>r.append(makeButton(label,state.route===id,()=>{state.route=id;save();render()})));const s=$('spoilerBtns');s.innerHTML='';spoilerList.forEach(([id,label])=>s.append(makeButton(label,state.spoiler===id,()=>{state.spoiler=id;save();render()})));const d=$('dlcBox');d.innerHTML='';dlcList.forEach(name=>{const l=document.createElement('label');l.className='t';const c=document.createElement('input');c.type='checkbox';c.checked=state.dlc.includes(name);c.onchange=()=>{state.dlc=c.checked?[...new Set([...state.dlc,name])]:state.dlc.filter(x=>x!==name);save();renderSummary();renderCompanions()};l.append(c,document.createTextNode(name));d.append(l)});const w=$('weaponBtns');w.innerHTML='';weaponList.forEach(([id,label])=>w.append(makeButton(label,state.weapon===id,()=>{state.weapon=id;save();renderWeapon()})));const b=$('buildBtns');b.innerHTML='';buildList.forEach(([id,label])=>b.append(makeButton(label,state.build===id,()=>{state.build=id;save();renderWeapon()})))}
function renderSummary(){const r=routes[state.route];$('summary').innerHTML='<span class="pill">Ending: '+r.title+'</span><span class="pill">Spoilers: '+spoilerList.find(x=>x[0]===state.spoiler)[1]+'</span><span class="pill">DLC: '+state.dlc.length+'/'+dlcList.length+'</span><p class="small" style="flex-basis:100%">'+r.desc+'</p>'}
function renderStatus(){const box=$('status');box.innerHTML='';Object.entries(routes[state.route].status).forEach(([n,k])=>{const p=document.createElement('span');p.className='pill '+k;p.textContent=n+': '+k.charAt(0).toUpperCase()+k.slice(1);box.append(p)})}
function allVisibleIds(){const ids=routes[state.route].steps.map(x=>x[3]);sideQuests.forEach(x=>ids.push(x[3]));const f=factionData[state.route];[...f.main,...f.side].forEach(x=>ids.push(x[2]));return [...new Set(ids)]}
function renderProgress(){const ids=allVisibleIds(),done=ids.filter(id=>state.done[id]).length,p=ids.length?Math.round(done/ids.length*100):0;$('progressBox').innerHTML='<p><strong class="count">'+done+'</strong> of <strong>'+ids.length+'</strong> visible checklist items done.</p><div class="progress"><div class="fill" style="width:'+p+'%"></div></div><p class="small">Saved locally on this browser.</p>'}
function renderSteps(){const box=$('steps');box.innerHTML='';routes[state.route].steps.forEach(x=>box.append(checkItem(x[0],x[1],x[2],x[3])))}
function renderWarnings(){const w=routes[state.route].warnings[state.spoiler],box=$('warnings');box.innerHTML='';const d=document.createElement('div');d.className='warn';d.innerHTML='<h3>⚠ '+w[0]+'</h3><p>'+w[1]+'</p>';box.append(d)}
function sideCategories(q){const cats=Array.isArray(q[1])?[...q[1]]:[q[1]];if(companionUnlockQuests.has(q[0])&&!cats.includes('companion'))cats.push('companion');return cats}
function sideDescription(q){if(q[0]==='The Big Dig')return q[2]+' Completing The Big Dig is required to unlock Hancock as a companion; depending on your final choice, Recruiting Hancock may follow before he joins.';if(q[0]==='Curtain Call')return q[2]+' Completing Curtain Call also makes Strong available as a companion.';if(q[0]==='Vault 81 and Hole in the Wall')return q[2]+' Completing Hole in the Wall makes Curie available as a companion.';return q[2]}
function sideType(q){const cats=sideCategories(q),labels=[];if(cats.includes('vault'))labels.push('Vault');else if(cats.includes('world'))labels.push('World / City');if(cats.includes('companion'))labels.push('Companion-related');return (labels.length?labels.join(' · '):'Independent')+' Side Quest'}
function sideCard(q){return checkItem(q[0],sideDescription(q),sideType(q),q[3])}
function renderSidePreview(){const box=$('sidePreview');box.innerHTML='';sideQuests.slice(0,8).forEach(q=>box.append(sideCard(q)))}
function renderSideList(){const box=$('sideList');box.innerHTML='';const term=($('sideSearch').value||'').toLowerCase().trim();const list=sideQuests.filter(q=>(sideFilter==='all'||sideCategories(q).includes(sideFilter))&&(!term||(q[0]+' '+sideDescription(q)).toLowerCase().includes(term)));if(!list.length){box.innerHTML='<div class="empty">No matching side quests.</div>';return}list.forEach(q=>box.append(sideCard(q)))}
function renderFaction(){const f=factionData[state.route];$('factionTitle').textContent=f.title+' questline';$('factionIntro').textContent=f.intro;const a=$('factionMain'),b=$('factionSide');a.innerHTML=b.innerHTML='';if(!f.main.length)a.innerHTML='<div class="empty">Pick a faction ending to see its dedicated storyline here.</div>';f.main.forEach(x=>a.append(checkItem(x[0],'',x[1],x[2])));f.side.forEach(x=>b.append(checkItem(x[0],'',x[1],x[2])))}
function noteCard(x){const d=document.createElement('div');d.className='note';d.innerHTML='<h3>'+x[0]+'</h3><p>'+x[1]+'</p>';return d}
function renderNotes(){const a=$('timedList'),b=$('notTimedList'),c=$('dangerList');a.innerHTML=b.innerHTML=c.innerHTML='';timed.forEach(x=>a.append(noteCard(x)));notTimed.forEach(x=>b.append(noteCard(x)));danger.forEach(x=>c.append(noteCard(x)))}
function renderWeapon(){document.querySelectorAll('#weaponBtns button').forEach((b,i)=>b.classList.toggle('active',weaponList[i][0]===state.weapon));document.querySelectorAll('#buildBtns button').forEach((b,i)=>b.classList.toggle('active',buildList[i][0]===state.build));const w=weapons[state.weapon][state.build],box=$('weaponOut');box.innerHTML='<div class="weapon"><h3>'+weaponList.find(x=>x[0]===state.weapon)[1]+' — '+buildList.find(x=>x[0]===state.build)[1]+'</h3><p>'+w[0]+'</p>'+w[1].map(x=>'<div class="slot"><strong>'+x[0]+'</strong><p>'+x[1]+'</p></div>').join('')+'<p class="small" style="margin-top:10px"><strong>Guide note:</strong> '+w[2]+'</p></div>'}

function companionHasNoAffinity(c){return c.perk==='No affinity perk'}
function companionAvailableByDlc(c){if(c.content==='Base Game')return true;if(c.content==='Automatron')return state.dlc.includes('Automatron');if(c.content==='Far Harbor')return state.dlc.includes('Far Harbor');if(c.content==='Nuka-World')return state.dlc.includes('Nuka-World');return true}
function companionMatchesFilter(c){if(companionFilter==='all')return true;if(companionFilter==='romance')return c.romance;if(companionFilter==='noaffinity')return companionHasNoAffinity(c);return c.content===companionFilter}
function companionProgressFor(id){return state.companionProgress[id]||{recruited:false,perk:false}}
function updateCompanionProgress(id,key,value){state.companionProgress[id]={...companionProgressFor(id),[key]:value};save();renderCompanions();if(state.selectedCompanion===id)renderCompanionDetail(id)}
function initials(name){return name.split(/\s|-/).filter(Boolean).map(x=>x[0]).join('').slice(0,3).toUpperCase()}
function companionCard(c){const p=companionProgressFor(c.id),card=document.createElement('article');card.className='companion-card';card.onclick=e=>{if(!e.target.closest('input')&&!e.target.closest('label'))renderCompanionDetail(c.id)};
 const portrait=document.createElement('button');portrait.className='companion-portrait';portrait.type='button';portrait.setAttribute('aria-label','Open '+c.name+' companion intel');const img=document.createElement('img');img.src=c.image;img.alt=c.name;const fb=document.createElement('span');fb.className='portrait-fallback';fb.textContent=initials(c.name);img.onerror=()=>{img.style.display='none';fb.style.display='grid'};portrait.append(img,fb);portrait.onclick=e=>{e.stopPropagation();renderCompanionDetail(c.id)};
 const body=document.createElement('div');body.className='companion-card-body';body.innerHTML='<div class="companion-card-title"><h3>'+c.name+'</h3><span class="tag">'+c.content+'</span></div><p>'+c.origin+'</p><div class="companion-card-tags"><span class="tag">'+(c.romance?'♥ Romance':'No romance')+'</span><span class="tag">'+(companionHasNoAffinity(c)?'No affinity':c.perk)+'</span></div>';
 const checks=document.createElement('div');checks.className='companion-checks';const r=document.createElement('label');r.innerHTML='<input type="checkbox" '+(p.recruited?'checked':'')+'> Recruited';r.querySelector('input').onchange=e=>updateCompanionProgress(c.id,'recruited',e.target.checked);checks.append(r);const pk=document.createElement('label');if(companionHasNoAffinity(c)){pk.className='disabled-check';pk.innerHTML='<input type="checkbox" disabled> No perk to earn'}else{pk.innerHTML='<input type="checkbox" '+(p.perk?'checked':'')+'> Perk earned';pk.querySelector('input').onchange=e=>updateCompanionProgress(c.id,'perk',e.target.checked)}checks.append(pk);
 const btn=document.createElement('button');btn.className='intel-button';btn.textContent='View Intel';btn.onclick=e=>{e.stopPropagation();renderCompanionDetail(c.id)};body.append(checks,btn);card.append(portrait,body);return card}
function renderCompanionFilters(){const box=$('companionFilterbar');box.innerHTML='';companionFilters.forEach(([id,label])=>box.append(makeButton(label,companionFilter===id,()=>{companionFilter=id;renderCompanionFilters();renderCompanionGrid()})))}
function renderCompanionGrid(){const box=$('companionGrid');box.innerHTML='';const term=($('companionSearch').value||'').toLowerCase().trim();const list=companions.filter(c=>companionAvailableByDlc(c)&&companionMatchesFilter(c)&&(!term||[c.name,c.content,c.origin,c.recruit,c.perk,c.perkEffect,...c.questline,...c.likes,...c.dislikes].join(' ').toLowerCase().includes(term)));if(!list.length){box.innerHTML='<div class="empty">No companions match that filter — or their DLC is currently toggled off.</div>';return}list.forEach(c=>box.append(companionCard(c)))}
function fillList(id,items){const el=$(id);el.innerHTML='';items.forEach(x=>{const li=document.createElement('li');li.textContent=x;el.append(li)})}
function renderCompanionDetail(id){const c=companions.find(x=>x.id===id);if(!c)return;state.selectedCompanion=id;save();const box=$('companionDetail');box.classList.remove('hidden');$('companionDetailName').textContent=c.name;$('companionOrigin').textContent=c.origin;$('companionRecruit').textContent=c.recruit;$('companionPerk').textContent=c.perk;$('companionPerkEffect').textContent=c.perkEffect;$('companionAffinityTip').textContent=c.affinityTip;$('companionNote').textContent=c.note;fillList('companionQuestline',c.questline);fillList('companionLikes',c.likes);fillList('companionDislikes',c.dislikes);const tags=$('companionDetailTags');tags.innerHTML='<span class="pill">'+c.content+'</span><span class="pill">'+(c.romance?'♥ Romanceable':'Not romanceable')+'</span><span class="pill">'+(companionHasNoAffinity(c)?'No affinity system':c.perk)+'</span>';const img=$('companionDetailImage'),fb=$('companionDetailFallback');img.style.display='block';fb.style.display='none';img.src=c.image;img.alt=c.name;fb.textContent=initials(c.name);img.onerror=()=>{img.style.display='none';fb.style.display='grid'};box.scrollIntoView({behavior:'smooth',block:'start'})}
function closeCompanionDetail(){state.selectedCompanion=null;save();$('companionDetail').classList.add('hidden')}
function renderCompanions(){renderCompanionFilters();renderCompanionGrid();if(state.selectedCompanion&&companions.some(c=>c.id===state.selectedCompanion&&companionAvailableByDlc(c)))renderCompanionDetail(state.selectedCompanion);else $('companionDetail').classList.add('hidden')}

function renderCurrentLists(){renderSteps();renderSidePreview();renderSideList();renderFaction()}
function render(){renderControls();renderSummary();renderStatus();renderProgress();renderSteps();renderWarnings();renderSidePreview();renderSideList();renderCompanions();renderFaction();renderNotes();renderWeapon();renderQuestPeek()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));document.querySelectorAll('.sideFilter').forEach(b=>b.onclick=()=>{sideFilter=b.dataset.filter;document.querySelectorAll('.sideFilter').forEach(x=>x.classList.toggle('active',x===b));renderSideList()});$('sideSearch').addEventListener('input',renderSideList);$('companionSearch').addEventListener('input',renderCompanionGrid);$('companionClose').addEventListener('click',closeCompanionDetail);render();