const KEY='fo4guide-v2';
const routeList=[['undecided','Undecided / Maximum Content'],['minutemen','Minutemen'],['railroad','Railroad'],['bos','Brotherhood of Steel'],['institute','Institute']];
const spoilerList=[['light','Light'],['warn','Warnings'],['full','Full']];
const dlcList=['Automatron','Far Harbor','Nuka-World','Vault-Tec Workshop','Wasteland Workshop','Contraptions Workshop'];
const sideQuests=[
['Benign Intervention','companion','Cait companion quest. Requires building enough affinity with Cait.','sq_benign'],
['The Big Dig','world','Goodneighbor side quest with a major choice near the end.','sq_bigdig'],
['Confidence Man','world','Diamond City side quest centered on Travis and the Dugout Inn.','sq_confidence'],
['Curtain Call','world','Trinity Tower rescue quest; also introduces Strong.','sq_curtain'],
['Detective Case Files: The Disappearing Act','world','Nick Valentine detective case.','sq_disappear'],
['Detective Case Files: The Gilded Grasshopper','world','Nick Valentine detective case and treasure hunt.','sq_grasshopper'],
['Detective Case Files: Long Time Coming','companion','Nick Valentine companion-related detective quest.','sq_longtime'],
['Diamond City Blues','world','Diamond City drug-deal quest with several branching outcomes.','sq_blues'],
["The Devil's Due",'world','Museum of Witchcraft / deathclaw egg side quest.','sq_devil'],
['Emergent Behavior','companion','Curie companion quest.','sq_emergent'],
['Here There Be Monsters','world','Boston Harbor / Yangtze side quest.','sq_monsters'],
['Human Error','world','Covenant side quest with a significant local choice.','sq_humanerror'],
['Kid in a Fridge','world','Optional Commonwealth side quest involving Billy.','sq_fridge'],
['Last Voyage of the U.S.S. Constitution','world','Long multi-stage quest aboard the U.S.S. Constitution.','sq_constitution'],
['Long Road Ahead','companion','MacCready companion quest.','sq_longroad'],
['The Secret of Cabot House','world','Cabot family questline with a major final choice.','sq_cabot'],
['The Silver Shroud','world','Goodneighbor superhero questline.','sq_shroud'],
['Vault 81 and Hole in the Wall','vault','Vault 81 quest chain; includes an important disease/reward choice.','sq_vault81']
];
const routes={
undecided:{title:'Maximum Content',desc:'Keep all major factions usable as long as possible.',status:{Minutemen:'friendly',Railroad:'friendly',Brotherhood:'friendly',Institute:'friendly'},steps:[['Out of Time','Start the Commonwealth.','Main Story','r_out'],['When Freedom Calls','Meet the Minutemen.','Minutemen','r_wfc'],['Fire Support + Call to Arms','Open Brotherhood access without committing to them.','Brotherhood','r_bosopen'],['Road to Freedom + Tradecraft','Join the Railroad early so their optional jobs are available.','Railroad','r_rrjoin'],['Reunions → Dangerous Minds → Hunter/Hunted','Progress the main story.','Main Story','r_mainmid'],['The Molecular Level','Reach the Institute stage. You do not have to build the teleporter with your final faction.','Main Story','r_molecular'],['Institutionalized','Meet the Institute and keep them non-hostile.','Main Story','r_institute'],['Blind Betrayal','Worth seeing before pushing Brotherhood hostility toward the Railroad.','Brotherhood','r_blind']],warnings:{light:['Tactical Thinking / Mass Fusion','These are major faction breakpoints. Stop and review first.'],warn:['Tactical Thinking / Mass Fusion','Do not push Tactical Thinking if you still want the Railroad; do not casually pick Mass Fusion/Spoils of War while keeping Institute/Brotherhood options open.'],full:['Maximum-content hard stops','For broad access: finish available side/misc faction jobs before pushing Tactical Thinking, Mass Fusion/Spoils of War, or the late stages of Underground Undercover.']}},
railroad:{title:'Railroad Ending',desc:'Prioritize the Railroad while still harvesting side content before hard lockouts.',status:{Minutemen:'friendly',Railroad:'friendly',Brotherhood:'neutral',Institute:'neutral'},steps:[['Out of Time → Reunions','Advance the early main story normally.','Main Story','rr_early'],['Road to Freedom','Find Railroad HQ.','Railroad','rr_road'],['Tradecraft','Officially establish Railroad access.','Railroad','rr_trade'],['Boston After Dark + early Railroad jobs','Do the optional Railroad work as it appears.','Railroad Side','rr_bad'],['Dangerous Minds → Hunter/Hunted → The Molecular Level','Push to Institute access.','Main Story','rr_mid'],['Underground Undercover','Begin the Railroad infiltration line while staying undercover in the Institute.','Railroad Main','rr_uu'],['Operation Ticonderoga','Do it when offered; do not ignore it once Underground Undercover advances too far.','Railroad Side','rr_ticon'],['Precipice of War','Late Railroad commitment.','Railroad Main','rr_precipice'],["Rockets' Red Glare",'Railroad endgame against the Brotherhood.','Railroad Main','rr_redglare'],['The Nuclear Option (Railroad)','Railroad ending.','Railroad Main','rr_nuclear']],warnings:{light:['Tactical Thinking','Brotherhood danger to your Railroad path.'],warn:['Tactical Thinking','If you want the Railroad ending, treat Tactical Thinking as a giant stop sign.'],full:['Railroad route protection','Stay on speaking terms with the Institute long enough to progress Underground Undercover. Do not let Brotherhood progression through Tactical Thinking wipe out your Railroad path. Operation Ticonderoga is also worth finishing before the late Underground Undercover trigger can make it fail.']}},
minutemen:{title:'Minutemen Ending',desc:'Flexible route with lots of optional faction content.',status:{Minutemen:'friendly',Railroad:'friendly',Brotherhood:'neutral',Institute:'neutral'},steps:[['When Freedom Calls → Sanctuary','Establish the Minutemen.','Minutemen','mm_start'],['The First Step / settlement recruitment','Build the network.','Minutemen','mm_first'],['Taking Independence','Retake the Castle.','Minutemen','mm_castle'],['Old Guns','Unlock artillery.','Minutemen','mm_oldguns'],['Main story through The Molecular Level','Reach the Institute stage while keeping other factions available.','Main Story','mm_main'],['Inside Job','Minutemen information-gathering step around Institute access.','Minutemen','mm_inside'],['Form Ranks → Defend the Castle','Commit to the late Minutemen path.','Minutemen Main','mm_defend'],['The Nuclear Option (Minutemen)','Minutemen ending.','Minutemen Main','mm_nuclear']],warnings:{light:['Nuka-World raider expansion','Check consequences before helping raiders take Commonwealth settlements.'],warn:['Nuka-World raider expansion','A Preston-friendly Minutemen run and Commonwealth raider settlements do not mix well.'],full:['Minutemen caution','This route is flexible, but Nuka-World raider expansion can damage the Preston relationship. Also finish any Brotherhood/Railroad content you care about before deliberately triggering endgame hostility.']}},
bos:{title:'Brotherhood of Steel Ending',desc:'Advance Brotherhood content while finishing Railroad/Institute business before bridges burn.',status:{Minutemen:'neutral',Railroad:'neutral',Brotherhood:'friendly',Institute:'hostile'},steps:[['Fire Support → Call to Arms','Open Brotherhood access.','Brotherhood','bos_start'],['Semper Invicta → Shadow of Steel → Tour of Duty','Advance onto the Prydwen.','Brotherhood','bos_prydwen'],['Show No Mercy','Continue the main Brotherhood chain.','Brotherhood','bos_mercy'],['From Within / Outside the Wire','Institute-related Brotherhood objectives.','Brotherhood','bos_inside'],['Liberty Reprimed → Blind Betrayal','Late Brotherhood story content.','Brotherhood','bos_liberty'],['Tactical Thinking','Hard Railroad danger point.','Brotherhood Danger','bos_tactical'],['Spoils of War → Ad Victoriam','Brotherhood endgame.','Brotherhood Main','bos_end'],['The Nuclear Option (Brotherhood)','Brotherhood ending.','Brotherhood Main','bos_nuclear']],warnings:{light:['Tactical Thinking','Major Railroad lockout danger.'],warn:['Tactical Thinking','Finish Railroad work you care about before advancing this quest.'],full:['Brotherhood route protection','Blind Betrayal is worth seeing before the final faction break. Tactical Thinking threatens the Railroad; Spoils of War is a major Institute split.']}},
institute:{title:'Institute Ending',desc:'Stay aligned with the Institute and finish outside-faction content before late hostility.',status:{Minutemen:'neutral',Railroad:'hostile',Brotherhood:'hostile',Institute:'friendly'},steps:[['Main story through Institutionalized','Reach and join the Institute.','Main Story','inst_start'],['Synth Retention','Institute main progression.','Institute','inst_synth'],['The Battle of Bunker Hill','Large faction-crossing story quest.','Institute','inst_bunker'],['Mankind - Redefined','Advance Institute leadership story.','Institute','inst_mankind'],['Mass Fusion','Major Brotherhood split.','Institute Danger','inst_mass'],['Pinned → Powering Up','Late Institute path.','Institute','inst_power'],['End of the Line → Airship Down','Late faction-destruction steps.','Institute Danger','inst_end'],['Nuclear Family','Institute ending.','Institute Main','inst_nuclear']],warnings:{light:['Mass Fusion / End of the Line','Major faction consequence points.'],warn:['Mass Fusion / End of the Line','Finish Brotherhood and Railroad content you want before these late Institute commitments.'],full:['Institute route protection','Mass Fusion is a major Brotherhood split, and End of the Line directly threatens the Railroad. Do outside-faction quests first if you want their rewards/content.']}}
};
