// Weapon Mod Lab data. Unique/legendary variants normally use their parent weapon platform's mod pool.
// This catalog covers the base game plus the user's official DLCs; Creation Club weapons are intentionally excluded.
const buildList=[
  ['general','General Use'],['damage','Raw Damage'],['vats','V.A.T.S.'],['stealth','Stealth'],['sniper','Sniper'],['automatic','Automatic'],['close','Close Range']
];

const weaponCatalog=[
// --- BALLISTIC PISTOLS -----------------------------------------------------
{id:'10mm',name:'10mm Pistol',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger when semi-auto · Commando with an automatic receiver',auto:true,suppressor:true,sniper:false,slots:[['Receiver','Controls damage and whether the pistol becomes automatic.'],['Barrel','Longer improves range; short/light is friendlier to V.A.T.S.'],['Grip','Comfort/recoil grips help accuracy; lighter grips suit V.A.T.S.'],['Magazine','Bigger magazines mean fewer reloads; quick-eject versions speed reloads.'],['Sights','Reflex is excellent for general/V.A.T.S.; scopes are rarely worth the weight here.'],['Muzzle','Suppressor for stealth; compensator-type options for recoil.']],acquire:'Very common from early enemies, containers and weapon vendors. The Vault 111 10mm makes an easy first platform for experimenting with mods.',aliases:['Wastelander’s Friend']},
{id:'44',name:'.44 Pistol',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger',auto:false,suppressor:false,sniper:false,slots:[['Receiver','Prioritize the strongest damage receiver you can obtain.'],['Barrel','Long barrels improve range and recoil; short barrels keep it handier.'],['Grip','Recoil-friendly grips make follow-up shots easier.'],['Sights','Reflex for V.A.T.S./close use; scope only if you truly use it at range.']],acquire:'Less common than the 10mm. Kellogg carries a guaranteed .44 at Fort Hagen, giving you a reliable donor platform later in the main story.',aliases:["Kellogg's Pistol",'The Gainer','Eddie’s Peace']},
{id:'pipe',name:'Pipe Gun',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock · Commando when automatic',auto:true,suppressor:true,sniper:true,transform:true,slots:[['Receiver','Can stay semi-auto or become automatic; choose based on Gunslinger/Rifleman vs Commando.'],['Barrel','Long for range; short/light for V.A.T.S. and close quarters.'],['Grip / Stock','This is important: a grip makes it a pistol, a stock makes it a rifle.'],['Magazine','Capacity and reload-speed choices are both useful.'],['Sights','Reflex for V.A.T.S.; scopes for rifle/sniper conversions.'],['Muzzle','Suppressor enables a very cheap early stealth gun.']],acquire:'One of the easiest donor weapons in the game: Raiders and low-level enemies carry pipe guns constantly. Check every unusually well-modded one before scrapping or selling it.',aliases:['Pipe pistol','Pipe rifle']},
{id:'pipe-bolt',name:'Pipe Bolt-Action',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock',auto:false,suppressor:true,sniper:true,transform:true,slots:[['Receiver','Damage upgrades matter most because every shot is slow.'],['Barrel','Long barrel strongly suits the rifle/sniper role.'],['Grip / Stock','Grip = pistol; stock = rifle and changes which damage perk applies.'],['Magazine','Capacity upgrades reduce how often the slow weapon needs attention.'],['Sights','Scopes are useful on rifle builds; reflex/iron sights for pistol use.'],['Muzzle','Suppressor turns it into a good early-budget stealth sniper.']],acquire:'Common on Raiders and in early weapon-vendor stock. Look for scoped/suppressed donor versions instead of rushing Gun Nut.',aliases:['Pipe bolt-action pistol','Pipe bolt-action rifle']},
{id:'pipe-revolver',name:'Pipe Revolver',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock',auto:false,suppressor:true,sniper:true,transform:true,slots:[['Receiver','Choose the strongest semi-auto damage option available.'],['Barrel','Long for range and stability; short for a compact sidearm.'],['Grip / Stock','Changes the weapon between pistol and rifle classification.'],['Sights','Reflex for pistol/V.A.T.S.; scope for rifle conversion.'],['Muzzle','Suppressor is especially useful on a hard-hitting stealth conversion.']],acquire:'Appears on Raiders and vendors as you level. A pre-modded donor can save several Gun Nut ranks.',aliases:['Pipe revolver pistol','Pipe revolver rifle']},
{id:'deliverer',name:'Deliverer',category:'Pistols',content:'Base Game',kind:'gun',perks:'Gun Nut for its advanced crafted mods',damagePerk:'Gunslinger',auto:false,suppressor:true,sniper:false,slots:[['Receiver','Use the strongest damage receiver available.'],['Barrel','Keep it compact; Deliverer is built around low AP cost rather than long-range sniping.'],['Grip','V.A.T.S.-friendly grip choices suit its special effect.'],['Magazine','More capacity is useful, but do not sacrifice its light responsive feel unnecessarily.'],['Sights','Reflex/iron-style sights fit its intended role.'],['Muzzle','Suppressor is the natural choice for stealth.']],acquire:'Guaranteed reward from the Railroad quest Tradecraft. Its low V.A.T.S. cost makes it one of the easiest weapons to understand as a dedicated stealth/V.A.T.S. sidearm.',aliases:['Deliverer pistol']},
{id:'western',name:'Western Revolver',category:'Pistols',content:'Nuka-World',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Gunslinger',auto:false,suppressor:false,sniper:false,slots:[['Receiver','Push damage; this is a slow, hard-hitting revolver.'],['Barrel','Long improves range; short keeps handling quick.'],['Grip','Recoil/accuracy upgrades help repeat shots.'],['Sights','Reflex-style aiming is the practical choice for most builds.']],acquire:'Found in Nuka-World, especially around Dry Rock Gulch and raider/vendor inventories. Buy or loot a well-modded revolver and use it as a donor.',aliases:[]},

// --- RIFLES ---------------------------------------------------------------
{id:'hunting',name:'Hunting Rifle',category:'Rifles',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman',auto:false,suppressor:true,sniper:true,slots:[['Receiver','Higher-damage receivers and caliber conversions are the main damage upgrade.'],['Barrel','Long barrel is ideal for range and sniper accuracy.'],['Stock','Full/recoil-friendly stocks improve stability.'],['Magazine','Larger/quick-eject magazines make the slow rifle less awkward.'],['Sights','Long/recon scope for sniping; reflex if used as a mid-range rifle.'],['Muzzle','Suppressor is excellent for a stealth sniper.']],acquire:'Common on Raiders/Gunners and at weapon vendors after the early game. A scoped hunting rifle is a very useful donor even if its receiver is weak.',aliases:['Sniper rifle','Reba','Reba II']},
{id:'combat',name:'Combat Rifle',category:'Rifles',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman when semi-auto · Commando when automatic',auto:true,suppressor:true,sniper:true,slots:[['Receiver','Choose strong semi-auto for Rifleman/sniping or automatic for Commando.'],['Barrel','Long for range; shorter/ported options for automatic handling.'],['Stock','Recoil-friendly stock is valuable, especially automatic.'],['Magazine','Large quick-eject is a very comfortable all-round choice.'],['Sights','Reflex for general/V.A.T.S.; long or recon scope for sniper builds.'],['Muzzle','Suppressor for stealth; compensator for loud recoil control.']],acquire:'Common mid-game on tougher enemies and vendors. Because many spawn already heavily modified, combat rifles are excellent donor weapons.',aliases:["Overseer's Guardian"]},
{id:'assault',name:'Assault Rifle',category:'Rifles',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman when semi-auto · Commando when automatic',auto:true,suppressor:true,sniper:true,slots:[['Receiver','Pick semi-auto damage or automatic fire to match your perk.'],['Barrel','Long/vented barrels help range and recoil.'],['Stock','Recoil control is especially useful on automatic receivers.'],['Magazine','High capacity works well for sustained fire.'],['Sights','Reflex for general combat; scopes if you deliberately keep it semi-auto.'],['Muzzle','Suppressor is possible; compensator-style recoil control is also strong.']],acquire:'Shows up more often on higher-level Gunners, Super Mutants and weapon vendors. Late-game donor rifles commonly carry expensive attachments.',aliases:[]},
{id:'submachine',name:'Submachine Gun',category:'Rifles',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Commando',auto:true,suppressor:true,sniper:false,slots:[['Receiver','Damage/automatic receiver upgrades are your priority.'],['Barrel','Favor recoil and handling over trying to make it a sniper.'],['Stock','Recoil control matters on long bursts.'],['Magazine','Large magazines suit the weapon’s high rate of fire.'],['Sights','Reflex/short-range sights are the natural fit.'],['Muzzle','Suppressor works well for a stealth Commando.']],acquire:'Common on Triggermen and around Goodneighbor/organized-crime encounters. Weapon vendors also provide useful donor versions.',aliases:['Spray n’ Pray','Silver Submachine Gun']},
{id:'railway',name:'Railway Rifle',category:'Rifles',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman',auto:false,suppressor:false,sniper:true,slots:[['Receiver','Damage-oriented upgrades are the main priority.'],['Barrel','Longer/stable barrel options support deliberate shots.'],['Stock','Use the stock that best stabilizes the rifle.'],['Sights','Scopes can make it a powerful novelty sniper; reflex is easier at medium range.']],acquire:'Prima lists a Railway Rifle reward after Underground Undercover. Once you have one, attached upgrades can be moved between Railway Rifles with the normal donor method.',aliases:[]},
{id:'gauss',name:'Gauss Rifle',category:'Rifles',content:'Base Game',kind:'gun',perks:'Advanced mods often require BOTH Gun Nut and Science!',damagePerk:'Rifleman',auto:false,suppressor:true,sniper:true,slots:[['Capacitors','Major damage/ammo-capacity upgrades; this is one of the most important slots.'],['Barrel','Long/shielded options support charged long-range fire.'],['Stock','Recoil and stability matter on a heavy charged rifle.'],['Sights','Recon/long scopes are excellent for sniping; reflex for V.A.T.S.'],['Muzzle','Suppressor enables absurdly strong stealth shots.']],acquire:'A late-game weapon found on high-level enemies such as Gunners and in advanced vendor inventories. Buying/looting a pre-modded Gauss rifle can bypass very high Gun Nut + Science! crafting requirements.',aliases:['Prototype PA77']},
{id:'handmade',name:'Handmade Rifle',category:'Rifles',content:'Nuka-World',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman when semi-auto · Commando when automatic',auto:true,suppressor:true,sniper:true,slots:[['Receiver','Very flexible: hard-hitting semi-auto or high-performance automatic.'],['Barrel','Long for precision; recoil-oriented barrels for automatic fire.'],['Stock','Recoil control is valuable on Commando builds.'],['Magazine','Large/quick magazines are excellent for sustained combat.'],['Sights','Reflex to scopes depending on role.'],['Muzzle','Suppressor makes it an exceptional stealth rifle.']],acquire:'Nuka-World raiders and market vendors supply these constantly. The Problem Solver and Splattercannon are unique handmade-rifle variants and use the same general mod family.',aliases:['The Problem Solver','Splattercannon']},
{id:'lever',name:'Lever-Action Rifle',category:'Rifles',content:'Far Harbor',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman',auto:false,suppressor:true,sniper:true,slots:[['Receiver','Prioritize damage because the rifle fires slowly.'],['Barrel','Long barrel suits its precision role.'],['Stock','Accuracy/stability upgrades are worthwhile.'],['Sights','Scope for sniper use; reflex for quick medium-range shots.'],['Muzzle','Suppressor is excellent for stealth.']],acquire:'Common in Far Harbor vendor inventories and on Island enemies as you progress. Old Reliable is a unique lever-action rifle sold in Acadia and can serve as a strong base weapon.',aliases:['Old Reliable']},
{id:'radium',name:'Radium Rifle',category:'Rifles',content:'Far Harbor',kind:'gun',perks:'Gun Nut for ballistic mods; some advanced radiation/tech mods also use Science!',damagePerk:'Rifleman when semi-auto · Commando when automatic',auto:true,suppressor:true,sniper:true,slots:[['Receiver','Choose semi-auto damage or automatic to match Rifleman/Commando.'],['Barrel','Range vs recoil/handling choice.'],['Stock','Recoil-friendly stock helps automatic builds.'],['Magazine','Capacity and quick reload are both valuable.'],['Sights','Reflex for general/V.A.T.S.; scope for precision.'],['Muzzle','Suppressor is a strong stealth option.']],acquire:'Children of Atom and Far Harbor vendors are the natural donor sources. Kiloton Radium Rifle is a unique version sold at the Nucleus.',aliases:['Kiloton Radium Rifle','Radical Conversion']},

// --- SHOTGUNS -------------------------------------------------------------
{id:'double-shotgun',name:'Double-Barrel Shotgun',category:'Shotguns',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman',auto:false,suppressor:false,sniper:false,slots:[['Receiver','Take the strongest damage option you can support.'],['Barrel','Short for brutal close range; longer for a little more reach.'],['Stock / Grip','Stock improves control; sawed-off/pistol-style setups are lighter but still function as a shotgun.'],['Sights','Keep sights simple; this is primarily a close-range weapon.']],acquire:'Extremely common on early Raiders. Check donor shotguns for better receivers/barrels before scrapping them.',aliases:[]},
{id:'combat-shotgun',name:'Combat Shotgun',category:'Shotguns',content:'Base Game',kind:'gun',perks:'Gun Nut for advanced crafted mods',damagePerk:'Rifleman when semi-auto · Commando with an automatic receiver',auto:true,suppressor:true,sniper:false,slots:[['Receiver','Powerful semi-auto for Rifleman or automatic for Commando.'],['Barrel','Longer improves range; shorter improves handling.'],['Stock','Recoil control matters greatly on automatic versions.'],['Magazine','Large/quick-eject magazines are a major quality-of-life upgrade.'],['Sights','Reflex is usually the most useful.'],['Muzzle','Suppressor enables stealth shotgun builds; compensator helps recoil.']],acquire:'Common on Gunners and stronger enemies later in the game. Le Fusil Terribles at Libertalia is a guaranteed unique Combat Shotgun platform.',aliases:['Le Fusil Terribles']},

// --- ENERGY / SPECIAL RANGED ---------------------------------------------
{id:'laser',name:'Laser Gun',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced energy mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock · Commando with an automatic barrel',auto:true,suppressor:false,sniper:true,transform:true,slots:[['Capacitor','Controls damage and special damage behavior.'],['Barrel','This slot can radically change the role: standard, automatic, splitter, sniper, etc.'],['Grip / Stock','Grip = pistol; stock = rifle and changes the damage perk.'],['Sights','Reflex for general/V.A.T.S.; scopes for precision.'],['Muzzle','Energy-specific muzzle attachments improve beam behavior rather than suppressing sound.']],acquire:'Synths, Brotherhood troops and weapon vendors supply laser donors. Righteous Authority from Call to Arms is a guaranteed unique Laser Gun platform.',aliases:['Righteous Authority','Old Faithful','Wazer Wifle']},
{id:'institute-laser',name:'Institute Laser',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced energy mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock · Commando with an automatic barrel',auto:true,suppressor:false,sniper:true,transform:true,slots:[['Capacitor','Damage upgrade.'],['Barrel','Controls automatic vs precision behavior.'],['Grip / Stock','Determines pistol or rifle classification.'],['Sights','Reflex/short scopes are generally more comfortable than bulky optics.'],['Muzzle','Energy beam-control choices rather than a suppressor.']],acquire:'Institute synths provide a nearly endless supply of donor weapons, making scavenging attachments especially easy if you do not invest heavily in Science!.',aliases:[]},
{id:'laser-musket',name:'Laser Musket',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced crafted mods',damagePerk:'Rifleman',auto:false,suppressor:false,sniper:true,slots:[['Capacitor / Crank','More cranks allow larger charged shots at the cost of time between attacks.'],['Barrel','Improve range/accuracy for deliberate shots.'],['Stock','Stability helps charged fire.'],['Sights','Scope for long-range Minutemen sniper use; reflex for general play.']],acquire:'Minutemen and the Museum of Freedom provide early Laser Muskets. Prima also lists the Automatic Laser Musket as a Minutemen endgame reward.',aliases:['Automatic Laser Musket']},
{id:'plasma',name:'Plasma Gun',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced energy mods',damagePerk:'Gunslinger with a grip · Rifleman with a stock · Commando with an automatic barrel',auto:true,suppressor:false,sniper:true,transform:true,slots:[['Capacitor','Main damage/special-effect slot.'],['Barrel','Can become sniper, automatic, flamer-like, or general-purpose.'],['Grip / Stock','Determines pistol vs rifle perk classification.'],['Sights','Reflex for V.A.T.S./general; scope for precision.']],acquire:'Appears later in the game on advanced enemies and at high-level weapon/Institute/Brotherhood vendors. Pre-modded plasma donors are especially valuable because Science! requirements climb quickly.',aliases:['Experiment 18-A','Sentinel’s Plasmacaster','Virgil’s Rifle']},
{id:'gamma',name:'Gamma Gun',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced crafted mods',damagePerk:'Gunslinger',auto:false,suppressor:false,sniper:false,slots:[['Dish','Changes radiation/projectile behavior and can add unusual special effects.'],['Grip','Improves handling/accuracy.'],['Sights','Short-range aiming upgrades are most practical.']],acquire:'Children of Atom are the best common donor source. The Cabot questline can reward a Gamma Gun, and Lorenzo’s Artifact is a special Gamma Gun modification worth preserving.',aliases:["Lorenzo's Artifact",'Zeta Gun']},
{id:'alien',name:'Alien Blaster',category:'Energy',content:'Base Game',kind:'energy',perks:'Science! for advanced crafted mods',damagePerk:'Gunslinger',auto:false,suppressor:false,sniper:false,slots:[['Magazine / Conversion','Can be adapted to use fusion cells when alien ammo becomes a problem.'],['Barrel','Damage/range upgrade.'],['Grip','Accuracy/handling.'],['Sights','Keep it light for a fast energy sidearm.']],acquire:'Prima lists the Alien Blaster in the cave by the alien crash site. Once you have the weapon, Science! lets you build its advanced modifications.',aliases:['Alien Blaster Pistol']},
{id:'syringer',name:'Syringer',category:'Special',content:'Base Game',kind:'special',perks:'Gun Nut is relevant to its limited weapon attachments; syringe ammunition is crafted separately',damagePerk:'Rifleman for the weapon itself; effects mainly come from the loaded syringe',auto:false,suppressor:false,sniper:true,slots:[['Barrel / Stock','Improve handling and accuracy rather than raw damage.'],['Sights','A scope helps land special syringe effects from range.'],['Ammo','The important customization is the syringe you load, crafted at a Chemistry Station.']],acquire:'Prima lists the Short Syringer Rifle as the reward for Hole in the Wall. Other Syringers can also appear in medical/science contexts and vendors.',aliases:['Short Syringer Rifle']},
{id:'cryolator',name:'Cryolator',category:'Special',content:'Base Game',kind:'energy',perks:'Science! for advanced crafted mods',damagePerk:'Heavy Gunner',auto:true,suppressor:false,sniper:false,slots:[['Barrel','Changes how the cryogenic attack is delivered.'],['Stock / Grip','Handling and accuracy.'],['Sights','Keep the weapon practical at close-to-medium range.']],acquire:'Guaranteed in Vault 111 inside the Overseer’s office behind a Master lock. Once recovered, its mods use the normal workbench/donor rules.',aliases:[]},
{id:'junk-jet',name:'Junk Jet',category:'Special',content:'Base Game',kind:'heavy',perks:'Gun Nut for advanced crafted mods',damagePerk:'Heavy Gunner',auto:false,suppressor:false,sniper:false,slots:[['Barrel','Improves performance of fired junk.'],['Stock','Handling/stability.'],['Sights','Aiming upgrades help with the unusual projectile arc.'],['Muzzle / Special','Use the weapon-specific upgrades rather than trying to fit normal rifle logic to it.']],acquire:'Prima places the Junk Jet in ArcJet Systems during Call to Arms. It is a guaranteed platform; mods can then be crafted or scavenged from another Junk Jet if you find one.',aliases:[]},
{id:'tesla',name:'Tesla Rifle',category:'Energy',content:'Automatron',kind:'energy',perks:'Science! for advanced crafted mods',damagePerk:'Rifleman / Commando depending on barrel behavior',auto:true,suppressor:false,sniper:false,slots:[['Barrel','The key slot: changes how electrical arcs are delivered.'],['Stock','Stability and handling.'],['Sights','Keep it practical for medium-range crowd control.']],acquire:'Obtained during Automatron from Ivey in Fort Hagen Hangar. Its special electrical behavior makes the barrel choice more important than trying to copy a normal rifle setup.',aliases:[]},
{id:'assaultron-head',name:'Salvaged Assaultron Head',category:'Special',content:'Automatron',kind:'special',perks:'No normal multi-slot mod tree',damagePerk:'Gunslinger',auto:false,suppressor:false,sniper:false,noMods:true,slots:[['Charging','Its main mechanic is charging shots, not conventional workbench customization.']],acquire:'Automatron weapon associated with Assaultrons/Rust Devils. Treat it as a special weapon rather than something you need to solve with Gun Nut or Science! mods.',aliases:[]},
{id:'thirst-zapper',name:'Thirst Zapper',category:'Special',content:'Nuka-World',kind:'special',perks:'Special Nuka-World upgrades; advanced ammunition options depend on Project Cobalt progression',damagePerk:'Varies with special ammunition',auto:false,suppressor:false,sniper:false,slots:[['Ammo / Project Cobalt','Its meaningful upgrades are the Nuka-Cola ammunition conversions, not normal receivers/barrels.']],acquire:'You receive the Thirst Zapper during Taken for a Ride. Later Nuka-World progression can unlock its damaging Nuka-Cola ammunition conversions.',aliases:['Nuka-Cola Thirst Zapper','Nuka-Cherry Thirst Zapper','Nuka-Quantum Thirst Zapper']},
{id:'paddle-ball',name:'Paddle Ball',category:'Special',content:'Nuka-World',kind:'special',perks:'Special Nuka-World mod tree',damagePerk:'Novelty/special weapon',auto:false,suppressor:false,sniper:false,slots:[['String / Ball upgrades','Nuka-World adds unusual damage-effect modifications rather than normal firearm parts.']],acquire:'Redeem one through the Nuka-Cade prize system, then use its special workbench modifications if you want to turn the novelty weapon into something more dangerous.',aliases:[]},

// --- HEAVY WEAPONS --------------------------------------------------------
{id:'minigun',name:'Minigun',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Gun Nut for advanced crafted mods',damagePerk:'Heavy Gunner',auto:true,suppressor:false,sniper:false,slots:[['Barrel','Changes damage/rate/accuracy characteristics; this is the major performance slot.'],['Sight','Targeting/aiming improvements help sustained fire.'],['Muzzle','Weapon-specific muzzle upgrades affect handling and bash behavior.']],acquire:'A guaranteed early Minigun appears during When Freedom Calls at the Museum of Freedom. Super Mutants and heavy-weapon enemies provide later donor versions.',aliases:['Ashmaker']},
{id:'gatling-laser',name:'Gatling Laser',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Science! for advanced crafted mods',damagePerk:'Heavy Gunner',auto:true,suppressor:false,sniper:false,slots:[['Receiver / Capacitor','Damage and fire behavior.'],['Barrel','Accuracy/rate-of-fire tradeoffs.'],['Sights','Improve sustained-fire tracking.'],['Muzzle','Beam-control upgrades.']],acquire:'Most strongly associated with high-level Brotherhood equipment and vendors such as Proctor Teagan. Final Judgment is a unique Gatling Laser carried by Elder Maxson.',aliases:['Final Judgment']},
{id:'flamer',name:'Flamer',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Gun Nut and/or Science! for advanced technology-heavy mods',damagePerk:'Heavy Gunner',auto:true,suppressor:false,sniper:false,slots:[['Tank','Fuel capacity.'],['Barrel / Nozzle','Changes range, spread and damage behavior.'],['Propellant / Special','Weapon-specific upgrades alter burn performance.']],acquire:'The Forged and Saugus Ironworks are natural sources for Flamers and donor parts. Weapon vendors can also stock them as you level.',aliases:[]},
{id:'missile',name:'Missile Launcher',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Gun Nut for advanced crafted mods; some targeting tech may also use Science!',damagePerk:'Heavy Gunner + Demolition Expert improves explosive damage',auto:false,suppressor:false,sniper:true,slots:[['Barrel','Standard vs multiple-shot capacity options.'],['Sights / Targeting','Targeting computer/scope-style upgrades are enormously more important here than on ordinary guns.'],['Muzzle','Weapon-specific explosive delivery upgrades.']],acquire:'Gunners, Super Mutants and advanced weapon vendors carry Missile Launchers. Prima lists Death From Above as a Prydwen missile launcher sold once you reach Paladin.',aliases:['Death From Above']},
{id:'fatman',name:'Fat Man',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Gun Nut and Science! may be required for advanced launcher modifications',damagePerk:'Heavy Gunner + Demolition Expert',auto:false,suppressor:false,sniper:false,slots:[['Launcher','Standard vs advanced launch behavior.'],['Special ammunition conversion','Nuka-World can add the Nuka-Nuke launcher modification through the Cappy questline.']],acquire:'Fixed Fat Man spawns exist throughout the Commonwealth; Prima specifically flags one at the Castle. Arturo sells the unique Big Boy, which still uses the Fat Man mod family.',aliases:['Big Boy','Nuka-Nuke Launcher','The Striker']},
{id:'broadsider',name:'Broadsider',category:'Heavy',content:'Base Game',kind:'heavy',perks:'Gun Nut for its advanced crafted mods',damagePerk:'Heavy Gunner + Demolition Expert',auto:false,suppressor:false,sniper:false,slots:[['Barrel / Canister','Weapon-specific upgrades improve cannon performance.'],['Grip / Stock','Handling.'],['Sights','Aiming helps compensate for the unusual cannonball projectile.']],acquire:'Prima lists the Broadsider as a reward from Last Voyage of the U.S.S. Constitution. Treat that quest reward as your guaranteed base weapon.',aliases:[]},
{id:'harpoon',name:'Harpoon Gun',category:'Heavy',content:'Far Harbor',kind:'heavy',perks:'Gun Nut for advanced crafted mods',damagePerk:'Heavy Gunner',auto:false,suppressor:false,sniper:true,slots:[['Harpoon / Flechette-style ammunition','Changes projectile behavior and can make recovered ammunition much easier to manage.'],['Barrel','Accuracy/range.'],['Sights','Useful because the projectile is slow and deliberate.']],acquire:'Far Harbor weapon vendors and Island enemies supply Harpoon Guns. Admiral’s Friend is a unique version sold in Far Harbor.',aliases:["Admiral's Friend"]},

// --- MELEE / UNARMED ------------------------------------------------------
{id:'bat',name:'Baseball Bat',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods; Nuka-World rocket/heated mods can also require Science!',damagePerk:'Big Leagues',slots:[['Material / Upgrade','Barbs, spikes, chains, blades and later DLC upgrades change damage/bleed/armor penetration.'],['Nuka-World rocket mods','Official DLC adds powerful rocket/heated bat options; some need both Blacksmith and Science!.']],acquire:'Bats are common and Moe Cronin in Diamond City specializes in them. Prima lists the 2076 World Series Baseball Bat under Jamaica Plain. Donor bats can carry transferable normal bat mods.',aliases:['2076 World Series Baseball Bat','Rockville Slugger','Cito’s Shiny Slugger']},
{id:'board',name:'Board',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Spikes/blades-style upgrades trade weight for damage, bleed or armor penetration.']],acquire:'Very common on Super Mutants, making donor boards easy to collect without spending perk points.',aliases:[]},
{id:'baton',name:'Security Baton',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Electrified/advanced baton modifications improve damage and utility.']],acquire:'Security locations and early Vault/robot facilities are natural sources. Keep a modded spare as a donor if you like the baton.',aliases:[]},
{id:'chinese-sword',name:'Chinese Officer Sword',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Sharpened/serrated/electrified-style upgrades improve raw damage and special effects.']],acquire:'Appears as loot and vendor stock; named variants use the same general sword platform. A donor sword with a high-end blade saves Blacksmith investment.',aliases:["General Chao's Revenge"]},
{id:'combat-knife',name:'Combat Knife',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Serrated/stealth-oriented blade upgrades increase damage and bleed.']],acquire:'Common on human enemies and vendors. Pickman’s Blade is a guaranteed unique Combat Knife reward if you side with Pickman.',aliases:["Pickman's Blade"]},
{id:'lead-pipe',name:'Lead Pipe',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Weighted/spiked-style upgrades improve damage and armor penetration.']],acquire:'Common low-level melee loot; donor versions are easy to find.',aliases:[]},
{id:'machete',name:'Machete',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Choose damage/bleed upgrades.'],['Unique donor mod','Kremvh’s Tooth carries the special Sacrificial Blade modification; preserve it rather than scrapping the weapon blindly.']],acquire:'Normal machetes are common. Prima places Kremvh’s Tooth in the deepest part of Dunwich Borers, making it an especially valuable unique donor weapon.',aliases:["Kremvh's Tooth"]},
{id:'pipe-wrench',name:'Pipe Wrench',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Hook/spike/heavy-style upgrades improve damage and special effects.']],acquire:'Common workshop/industrial loot. Prima lists Big Jim at Walden Pond as a unique Pipe Wrench.',aliases:['Big Jim']},
{id:'pool-cue',name:'Pool Cue',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Sharper/heavier tips improve damage.']],acquire:'Common around bars, pool rooms and low-level melee enemies; easy donor weapon.',aliases:[]},
{id:'rev-sword',name:'Revolutionary Sword',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Damage/electrified-style upgrades are the meaningful choice.']],acquire:'Found in historical locations, loot and vendors. A high-end blade can be transferred from another Revolutionary Sword.',aliases:[]},
{id:'ripper',name:'Ripper',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Extended/curved-style blade upgrades improve the continuous-contact damage.']],acquire:'Rarer industrial/melee weapon found in higher-level loot and weapon vendors. Check every donor Ripper for its blade attachment.',aliases:[]},
{id:'rolling-pin',name:'Rolling Pin',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Spiked/sharp upgrades turn the joke weapon into a somewhat less joking weapon.']],acquire:'Kitchens, domestic locations and general loot. Mods are simple enough that donor scavenging is easy.',aliases:[]},
{id:'sledge',name:'Sledgehammer',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Head / Upgrade','Heavy, spiked and advanced heads trade weight for substantial damage.']],acquire:'Very common on Super Mutants and heavy melee enemies. Higher-level enemies often provide excellent donor heads.',aliases:[]},
{id:'super-sledge',name:'Super Sledge',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Heating / Rocket assembly','Advanced head/rocket modifications increase already-high damage.']],acquire:'Commoner on high-level Super Mutants and heavy melee vendors. Because it is expensive to craft up, donor Super Sledges are worth checking.',aliases:[]},
{id:'switchblade',name:'Switchblade',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Serrated-style upgrade improves bleed/damage.']],acquire:'Common Raider/Triggerman melee loot and inexpensive vendor stock.',aliases:[]},
{id:'tire-iron',name:'Tire Iron',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Bladed/heavy modifications improve damage.']],acquire:'Common roadside, Raider and workshop loot; easy donor source.',aliases:[]},
{id:'walking-cane',name:'Walking Cane',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Upgrade','Spiked/barbed-style improvements add damage.']],acquire:'Found as general loot and vendor stock. Donor scavenging is usually easier than investing perks specifically for it.',aliases:[]},
{id:'shishkebab',name:'Shishkebab',category:'Melee',content:'Base Game',kind:'melee',perks:'Blacksmith (and Science! for some advanced technology mods)',damagePerk:'Big Leagues',slots:[['Flame Jets','The signature upgrade increases its fire-based damage output.']],acquire:'Prima lists Shishkebab on Slag in the Saugus Ironworks Blast Furnace, giving you a guaranteed source during Out of the Fire.',aliases:[]},
{id:'assaultron-blade',name:'Assaultron Blade',category:'Melee',content:'Automatron',kind:'melee',perks:'Blacksmith / Science! depending on advanced blade technology',damagePerk:'Big Leagues',slots:[['Blade','Advanced/electrified blade options improve damage.']],acquire:'Automatron robots and Rust Devil content are the natural sources. Looting a modded blade lets you transfer the attachment normally.',aliases:[]},
{id:'buzz-blade',name:'Mr. Handy Buzz Blade',category:'Melee',content:'Automatron',kind:'melee',perks:'Blacksmith / Science! for advanced powered mods',damagePerk:'Big Leagues',slots:[['Blade','Powered blade upgrades alter continuous-contact damage.']],acquire:'Automatron/Rust Devil encounters provide the weapon. Treat high-level enemy drops as donor weapons before selling them.',aliases:[]},
{id:'meat-hook',name:'Meat Hook',category:'Melee',content:'Far Harbor',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Iron Fist',slots:[['Hook','Additional hook/piercing upgrades improve damage.']],acquire:'Common on Far Harbor Trappers and at Island vendors. It counts with unarmed-style damage perks despite being a handheld weapon.',aliases:["Butcher's Hook"]},
{id:'pole-hook',name:'Pole Hook',category:'Melee',content:'Far Harbor',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Hook','Puncturing/advanced hook upgrades improve damage and armor penetration.']],acquire:'Far Harbor Trappers and vendors are the main donor source.',aliases:[]},
{id:'disciples-blade',name:'Disciples Blade',category:'Melee',content:'Nuka-World',kind:'melee',perks:'Blacksmith for advanced mods',damagePerk:'Big Leagues',slots:[['Blade','Advanced blades push the weapon’s already-high fast melee damage.']],acquire:'Disciples gang members and Nuka-World raider vendors provide the platform and donor blades.',aliases:['Throatslicer']},

// --- UNARMED --------------------------------------------------------------
{id:'boxing-glove',name:'Boxing Glove',category:'Unarmed',content:'Base Game',kind:'unarmed',perks:'Blacksmith for advanced mods',damagePerk:'Iron Fist',slots:[['Lining / Upgrade','Weighted/puncturing-style upgrades add damage and special effects.']],acquire:'Found in gyms, melee loot and vendors. Donor gloves are usually inexpensive.',aliases:[]},
{id:'deathclaw',name:'Deathclaw Gauntlet',category:'Unarmed',content:'Base Game',kind:'unarmed',perks:'Blacksmith for advanced mods',damagePerk:'Iron Fist',slots:[['Claw','Extra claw upgrades improve damage.']],acquire:'Prima lists a Deathclaw Gauntlet reward for The Devil’s Due. Other gauntlets can appear in high-level loot.',aliases:[]},
{id:'knuckles',name:'Knuckles',category:'Unarmed',content:'Base Game',kind:'unarmed',perks:'Blacksmith for advanced mods',damagePerk:'Iron Fist',slots:[['Upgrade','Bladed/spiked/weighted variants improve damage and bleed/armor penetration.']],acquire:'Common low-level unarmed weapon in Raider loot and vendors.',aliases:[]},
{id:'power-fist',name:'Power Fist',category:'Unarmed',content:'Base Game',kind:'unarmed',perks:'Blacksmith for advanced mods; powered options can involve Science!',damagePerk:'Iron Fist',slots:[['Piston / Plate','Puncturing/heating-style upgrades improve damage and armor penetration.']],acquire:'Swan in Boston Common carries the guaranteed unique Furious Power Fist, giving you a strong platform without waiting for random loot.',aliases:['Furious Power Fist']},

// --- LIMITED / NO NORMAL MOD TREE ----------------------------------------
{id:'flare',name:'Flare Gun',category:'Special',content:'Base Game',kind:'special',perks:'No normal weapon-mod tree',damagePerk:'Utility weapon',noMods:true,slots:[['Utility','Primarily used for Minutemen flare support rather than custom weapon building.']],acquire:'Received through the Minutemen questline. There is no complex receiver/barrel mod puzzle to solve here.',aliases:[]},
{id:'acid-soaker',name:'Acid Soaker',category:'Special',content:'Nuka-World',kind:'special',perks:'No normal multi-slot weapon-mod tree',damagePerk:'Special weapon',noMods:true,slots:[['Ammo','Its main limitation is specialized acid ammunition rather than attachments.']],acquire:'Nuka-Cade prize weapon. Treat it as a novelty/special-ammo weapon, not a Gun Nut project.',aliases:[]}
];

const weaponList=weaponCatalog.map(w=>[w.id,w.name]);
const weaponCategories=['All','Pistols','Rifles','Shotguns','Energy','Heavy','Melee','Unarmed','Special'];

function weaponBuildProfile(w,build){
  const name=w.name;
  if(w.noMods){
    return ['This weapon has no normal multi-slot mod tree.',[['What matters',w.slots.map(x=>x[0]+': '+x[1]).join(' ')]],w.acquire];
  }
  if(w.kind==='melee'||w.kind==='unarmed'){
    if(build==='sniper'||build==='automatic')return ['That build goal does not really apply to '+name+'.',[['Better goal','Use General, Raw Damage, V.A.T.S., Stealth or Close Range instead.']],w.damagePerk+' is the relevant damage perk.'];
    const plan=build==='damage'?'Choose the highest damage/bleed/armor-piercing upgrade you can obtain.':build==='vats'?'Favor a strong damage mod without needlessly adding weight; V.A.T.S. performance comes mostly from your SPECIAL/perks.':build==='stealth'?'Melee attacks are naturally quiet; prioritize strong first-hit damage rather than searching for a suppressor that does not exist.':build==='close'?'This is already a close-range weapon: maximize practical damage and useful bleed/armor penetration.':'Use the strongest affordable upgrade that matches whether you value raw damage, bleed or armor penetration.';
    return ['Melee mod plan.',[['Upgrade priority',plan],['Damage perk',w.damagePerk],['Crafting perk',w.perks]],'Donor method still works: replace an attached melee upgrade with a basic one, then reuse the removed mod on another compatible '+name+'.'];
  }
  if(w.kind==='heavy'){
    let plan='Prioritize the weapon-specific damage/capacity/accuracy upgrades; heavy weapons do not follow normal pistol/rifle receiver logic.';
    if(build==='vats')plan='Heavy weapons are usually AP-hungry in V.A.T.S.; favor accuracy and avoid building around V.A.T.S. unless this is a deliberate challenge build.';
    if(build==='stealth')plan='Most heavy weapons are poor stealth choices. Use another suppressed weapon for opening shots, then switch to this when combat starts.';
    if(build==='sniper')plan=w.sniper?'Use the best aiming/targeting system and range-oriented parts; explosive projectile travel still matters.':'This is not a natural sniper platform; use its intended sustained-fire/explosive role.';
    if(build==='automatic')plan=w.auto?'It is already an automatic/sustained-fire weapon: focus on recoil, capacity and sustained damage.':'This platform does not become a normal automatic firearm.';
    if(build==='damage')plan='Take the strongest damage-focused weapon-specific upgrades you can support, then let Heavy Gunner (and Demolition Expert for explosives) do the rest.';
    if(build==='close')plan='Be careful: explosive heavy weapons can hurt you at close range. Non-explosive heavies should favor handling/spread control.';
    return ['Heavy weapon plan.',[['Primary goal',plan],['Damage perk',w.damagePerk],['Crafting',w.perks]],'Heavy weapon donor drops become much better at higher levels, so inspect enemy weapons before selling them.'];
  }
  if(w.kind==='special'){
    return ['Special weapon: follow its own mechanics rather than normal rifle rules.',w.slots.map(x=>[x[0],x[1]]),w.acquire];
  }
  const isEnergy=w.kind==='energy';
  let slots=[];let intro='Flexible '+(isEnergy?'energy':'firearm')+' setup.';
  if(build==='general')slots=[['Damage / Receiver','Use a reliable damage upgrade that matches your damage perk.'],['Barrel','Medium/long for a comfortable balance of range and handling.'],['Sight','Reflex is the easiest all-purpose choice.'],['Magazine / Stock','Favor comfort: quick reload, useful capacity and recoil control.']];
  if(build==='damage')slots=[['Damage / Receiver','Use the strongest non-automatic damage option unless you are specifically a Commando build.'],['Barrel','Long/stable if it increases effective range and accuracy.'],['Other slots','Do not sacrifice huge handling/AP costs for tiny paper-stat gains unless you enjoy the feel.']];
  if(build==='vats')slots=[['Receiver','Good damage without unnecessary weight.'],['Barrel','Short/light options often reduce AP cost and keep V.A.T.S. efficient.'],['Sight','Reflex sights are usually V.A.T.S.-friendly.'],['Magazine / Grip','Quick/light handling tends to matter more than maximum capacity.']];
  if(build==='stealth')slots=[['Receiver','High single-shot damage makes sneak multipliers count.'],['Muzzle',w.suppressor?'Use a suppressor. This is the defining stealth attachment.':'No suppressor is available on this platform; rely on positioning and sneak perks instead.'],['Sight','Reflex for close/V.A.T.S. stealth; scope for deliberate long shots.'],['Barrel','Long for manual sniping, light/short for V.A.T.S.-heavy stealth.']];
  if(build==='sniper')slots=w.sniper?[['Receiver','Strong semi-auto / charged damage; avoid automatic if you want Rifleman/Sniper behavior.'],['Barrel','Long/sniper barrel.'],['Stock','Full accuracy/recoil stock where available.'],['Sight','Long or recon scope.'],['Muzzle',w.suppressor?'Suppressor for stealth sniping.':'No suppressor on this platform.']]:[['Suggestion','This weapon is not a natural sniper. Pick a Hunting Rifle, Combat Rifle, Gauss Rifle, Laser/Plasma sniper configuration, Lever-Action Rifle, or similar platform.']];
  if(build==='automatic')slots=w.auto?[['Receiver / Barrel','Choose the weapon’s automatic option.'],['Recoil control','Stock/barrel/compensator choices become much more important.'],['Sight','Reflex is much easier to manage than a long scope.'],['Magazine','Larger or quick-eject magazines reduce downtime.']]:[['Suggestion','This weapon does not have a normal automatic conversion. Do not force Commando onto it.']];
  if(build==='close')slots=[['Receiver','High practical DPS matters more than long-range precision.'],['Barrel','Short/handling-friendly barrel where available.'],['Sight','Reflex or simple sights.'],['Recoil / Spread','Use stock/grip/muzzle choices that make rapid follow-up shots comfortable.']];
  return [intro,slots,'Crafting: '+w.perks+'. Damage perk: '+w.damagePerk+'. '+(w.transform?'Remember that changing grip ↔ stock can change whether Gunslinger or Rifleman applies.':'')];
}

const weapons={};
weaponCatalog.forEach(w=>{
  weapons[w.id]={};
  buildList.forEach(([id])=>weapons[w.id][id]=weaponBuildProfile(w,id));
});
